name: Illumos build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feat/*'
jobs:
  build:
    name: illumos build
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
        fail-fast: false
        matrix:

          target:
            # Illumos targets ðŸŒž
                - x86_64-unknown-illumos # 64-bit Illumos on x86-64     âœ… Tested

          include:
            # FreeBSD targets ðŸ¬
            - target: x86_64-unknown-illumos
              os: ubuntu-latest
              cross: true
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Update version number
        id: update-version
        run: |
          NEW_VERSION=$(grep version Cargo.toml | sed -n 2p | cut -d '"' -f 2)
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
        shell: /bin/bash -e {0}

      - name: Build
        run: cargo build

      - name: Upload binary to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: ssg-${{ matrix.target }}-v${{ env.VERSION }}
          path: target/release/ssg
          archive_format: tar.gz

      - name: Verify upload (tar.gz)
        if: ${{ steps.upload_tar.result == 'success' }}
        run: echo "Tar.gz archive uploaded successfully."
        shell: /bin/bash -e {0}

      - name: Print error (tar.gz)
        if: ${{ steps.upload_tar.result != 'success' }}
        run: echo "Tar.gz archive upload failed with exit code ${{ steps.upload_tar.exit_code }}."
        shell: /bin/bash -e {0}

      - name: Upload binary to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: ssg-${{ matrix.target }}-v${{ env.VERSION }}
          path: target/release/ssg
          archive_format: zip

      - name: Verify upload (zip)
        if: ${{ steps.upload_zip.result == 'success' }}
        run: echo "Zip archive uploaded successfully."
        shell: /bin/bash -e {0}

      - name: Print error (zip)
        if: ${{ steps.upload_zip.result != 'success' }}
        run: echo "Zip archive upload failed with exit code ${{ steps.upload_zip.exit_code }}."
        shell: /bin/bash -e {0}
